---
title: "Untitled"
format: html
editor: visual
---

### Substrate dispense with OT-2

1.  Substrate 1500개 1 Plate당 80개 (8\*10)\*20
2.  Sensor cell 2종류
3.  Cell 당 새로운 (96 well plate)\*2 각 198 ul 분주 (Duplicate)
4.  Substrate 5 ul에 DMSO 5 ul 추가 희석
5.  희석 된 Substrate 2 ul씩 분주된 Cell에 추가
    -   서로 다른 Seonsor Cell은 Tip 변경

### Pseudocode

1.  Sensor Cell 1종 당 300P 사용하여 새로운 96 well plate 2개에 Cell 198 ul 씩 분주 (*8\*12)\**2
    -   팁 몇번 사용할지 결정 필요
> Loop
2.  20P 사용 Substrate plate에 DMSO 5 ul 씩 추가 후 Mix
3.  팁 갈지 않고 Substrate Mixture 1번 sensor plate 2개에 Dispense 2 ul 씩 (2개 plate)
4.  새팁 사용하여 Substrate Mixture 2번 sensor plate 2개에 Dispense 2 ul 씩 (2개 plate)
> Loop end
5.  플레이트, 팁 변경 재 시작

### Deck Position

| Labware                  | Deck 공간 | 교체 주기     |
|--------------------------|-----------|---------------|
| 300P 4줄                 | 1개       | 3회 마다 교체 |
| 20P 20줄                 | 2개       | 1회 마다 교체 |
| 96 well plate 4개        | 4개       | 1회 마다 교체 |
| 기질 Plate 1개           | 1개       | 1회 마다 교체 |
| WT Cell reservoir 1개    | 1개       | 1회 마다 교체 |
| E135K Cell reservoir 1개 | 1개       | 1회 마다 교체 |
| DMSO reservoir 1개       | 1개       | 1회 마다 교체 |

-   남는 20P 2줄은 모아서 사용하기
-   DMSO 는 Cell reservoir 에 같이 넣어 사용

### Code

1 - 5번까지를 한 Cycle로 해서 함수로 작성

-   1 cycle 종료 시 마다 정지 후 labware 교체 알림
-   300P 팁만 3회 교체주기 카운팅하여 알려주기
